# Generated by Django 3.1 on 2020-08-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('owner', models.CharField(max_length=60, verbose_name='Owner')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('stations', models.IntegerField(verbose_name='Stations')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, unique=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, unique=True, verbose_name='Longitude')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fazenda')),
            ],
        ),
    ]
